# syntax=docker/dockerfile:1

FROM golang:1.24 AS builder

WORKDIR /app

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /mqtt-test

# Final minimal image
FROM gcr.io/distroless/static

COPY --from=builder /mqtt-test /mqtt-test
COPY --from=builder /app/*.html /

ENTRYPOINT ["/mqtt-test"]